version: '3.7'
services:
    #Server#############################################################
    php:
        build: ./docker/php/
        restart: always
        environment:
            TIMEZONE: Europe/Moscow
        volumes:
        - ./docker/php/php.ini:/usr/local/etc/php/php.ini:ro
        - ./app:/var/www/app
        working_dir: /var/www/app
    webserver:
        image: nginx:1.15
        restart: always
        depends_on:
        - php
        volumes:
        - ./docker/nginx/app.conf:/etc/nginx/conf.d/default.conf:ro
        - ./app:/var/www/app
        ports:
        - 8080:80
    #Assets#############################################################





    #DB#################################################################
    db:
        image: mariadb
        restart: always
        volumes:
        - db:/var/lib/mysql # а вот тут я не понял O_o / при попытке прописать относительный путь хоста(./) меня посылает
        - ./docker/mariadb/conf.d:/etc/mysql/conf.d
        environment:
            MYSQL_ROOT_PASSWORD: example
            MYSQL_DATABASE: db
            MYSQL_USER: db
            MYSQL_PASSWORD: db
    adminer:
        image: adminer
        restart: always
        volumes:
        - ./docker/adminer/adminer.css:/var/www/html/adminer.css
        depends_on:
        - db
        ports:
        - 8090:8080

volumes:
    app:
    db:
